### ISSUE TITLE
NodeBots SF February 2015 Meetup

### ISSUE THREAD

**Issue by bryan-m-hughes** [nodebots/sf#20]
For this meetup, we plan to solder all the things! Well, hopefully not _all_ the things... :)

I'm still thinking on how exactly to structure it, but here's my current train of thought:
- Start with a mini-lecture on what soldering is and safety, then move on to hands on
- Have some sort of basic circuit that we will be soldering...maybe a blinky light powered by a 555 timer or something
    - If we want to get really fancy, maybe a custom PCM from http://www.oshpark.com/. We could probably get them for $3-5 for the kinds of boards and quantity we will want, and it would really make an impression. Plus, they're purple like our logo!
- All through-hole, no surface mount (unless we want it as an "advanced" challenge?)

For this meetup, we'll need a venue and a hardware sponsor. At minimum, we will need someone to cover the consumable hardware (boards, components, solder, wick, etc), but maybe also irons?

I'll be going through the inventory later this week for the JSFest event, and I'll make sure to inventory our soldering supplies and come up with a BOM for the meetup.

Thoughts on a venue to reach out to?

**Comment by bryan-m-hughes** [comment]
I just created the meetup page for this event, and will announce in the morning: http://www.meetup.com/nodebotssf/events/220265810/

We still need hardware, and someone to sponsor the hardware. I'll try and get the circuit and boards designed in the next few days...gotta get through ForwardJS first though.

Would someone be willing to do some research into soldering irons? How many do you think we should get?

**Comment by bryan-m-hughes** [comment]
Speaking of ForwardJS, PubNub agreed to sponsor the food for the workshop, so we're going to donate the proceeds to charity. Dave recommended Black Girls Code and SF AIDS Foundation, which I think is a great choice. What does everyone else think?

**Comment by bryan-m-hughes** [comment]
I put together a list of hardware that I think we'll need.

![Parts List](https://cloud.githubusercontent.com/assets/1141386/6123118/0f94fb20-b0b3-11e4-90ca-ed676cfa7f27.png)

My thoughts are that we will use the Adafruit perma-proto boards for this lesson, which are actually pretty awesome. It would have been nice to do custom printed PCBs, but I ran out of time and missed the deadline to get stuff from OSH park on time (and the others are way expensive at this late date).

For the circuit, I'm thinking about keeping it simple and just doing an LED powered by a 9V battery. This will mean soldering one LED, one resistor, and headers for plugging in the battery. If people want to do more, or we have extra time, we can wire up multiple LEDs in parallel for fun colors.

We currently have 37 people registered, so I'm guessing 15-20 will show. I think it's overkill to try and get soldering irons for everyone, so my list has 10 irons. I'm thinking people can buddy up and take turns building their circuits.

The parts not on the list that adafruit doesn't have are solid flux for tip conditioning (my preferred way, and I do want to spend time talking about caring for irons so that tips last more than a few weeks), LEDs, resistors, and AAA batteries. I'm thinking we can just get these at Fry's or Radio Shack.

What does everyone else think?

We also need to find a hardware sponsor. Any suggestions?

**Comment by bryan-m-hughes** [comment]
So I was thinking about it some more, and I want to add a bit to the workshop: removing the LED and replacing it with a different color so we can teach people about solder wick and solder suckers. As such, we will need to increase the number of wicks and suckers to 10 each, raising the total to $508 from AdaFruit.

**Comment by bryan-m-hughes** [comment]
Here's an updated BOM:

Soldering stations:

Item | URL | Unit Cost (for 10+)
-------|-------|--------------------
Iron | https://www.adafruit.com/products/2163 | $22.46
Stand | https://www.adafruit.com/products/150 | $5.40
Solder Sucker | https://www.adafruit.com/products/148 | $4.50 
Solder | https://www.adafruit.com/products/1886 | $5.36
Wick | https://www.adafruit.com/products/149 | $2.70
Solid Flux/Tip Conditioner | Not on adafruit | couple of bucks

Project hardware

Item | URL | Qty | Total Cost
-------|-------|-------|--------------------
Coin cell battery holder | https://www.adafruit.com/products/783 | 30 | $52.80
Coin cell batteries | https://www.adafruit.com/products/654 | 30 | $54.00
White LED Pack | https://www.adafruit.com/products/754 | 1 | $6.95
Green LED Pack | https://www.adafruit.com/products/300 | 1 | $8.00
Blue LED Pack | https://www.adafruit.com/products/301 | 1 | $8.00
330 ohm Resistors | Not on adafruit | 50 | cheap
Permaproto Boards | https://www.adafruit.com/products/589 | 10 | $76.50

I capped the number of RSVP's at 40 because I don't want this group to be too large, both for cost and safety reasons (amount of fumes, chances of someone getting burned, etc). As a result, I expect about 20-25 to show up.

**Comment by bryan-m-hughes** [comment]
@emilyrose is still working on a possible hardware sponsorship, but I went ahead and placed the adafruit order today and stopped by Fry's to make sure we have everything in time for the event. Total cost for everything was $759.35

**Comment by bryan-m-hughes** [comment]
BTW, hardware has been ordered and shipped, and Spark is going to cover the hardware (thanks @emilyrose!). It'll be close, but it'll be arriving at the Rdio office on Thursday.

**Comment by TheAlphaNerd** [comment]
Woohoo!

**Comment by melanielok** [comment]
Nice!  I'm sad I can't make it.

**Comment by bryan-m-hughes** [comment]
Hardware is in! I'll planning on getting there around 5:30 tonight.

**Comment by dshaw** [comment]
Woohoo! Just in time.

Unfortunately, I blew my back out on Tuesday and will not be able to make it out tonight. I'll miss you all. Have a great meetup!
