### ISSUE TITLE
NodeBots SF 2015 planning

### ISSUE THREAD

**Issue by bryan-m-hughes** [nodebots/sf#23]
Let's do another planning meeting to get the next few months of meetups figured out. I suggest we do one in early January, perhaps January 8th? That is one week before the January NodeBots SF meetup on soldering.

We can host it at Rdio or Famo.us, but we could also chat over dinner somewhere and keep it casual (HT to @TheAlphaNerd for this idea).

**Comment by voodootikigod** [comment]
Hey just a heads up I am definitely going to be there for reactjsconf
would love to do at the very least a beer/food with the NodeBots SF crew.
Let me know what works!!  Cheers

**Comment by bryan-m-hughes** [comment]
@voodootikigod Will you be able to put together a talk for 1/29(ish)? Speakers choice on topics :) I think we would all prefer to make this the January meetup.

@Frijol (or @morganrallen) have you had a chance to get in touch with your contacts at Supply Frame about hosting yet?

**Comment by morganrallen** [comment]
I'll shoot Alek and Matt a message.

On Sun, Jan 4, 2015 at 2:18 PM, Bryan Hughes <notifications@github.com>
wrote:

> @voodootikigod <https://github.com/voodootikigod> Will you be able to put
> together a talk for 1/29(ish)? Speakers choice on topics :) I think we
> would all prefer to make this the January meetup.
>
> @Frijol <https://github.com/Frijol> (or @morganrallen
> <https://github.com/morganrallen>) have you had a chance to get in touch
> with your contacts at Supply Frame about hosting yet?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodebots/sf/issues/23#issuecomment-68652021>.
>



-- 
http://ithoughtyouweretherobot.com
Metal and Wire

http://nolonelyguineapigs.com/
Wandering and Rambling

http://morglog.org
Old and Neglected.

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: OpenPGP.js v.1.20121007
Comment: http://openpgpjs.org

xsBNBFG3btUBB/9+/WJNOSIuc/praKPaPOweqXV5s7PGRD+HAnNWF/19YAY3
AFtfeoelhhY4sMJoobTaJzcZojznZ1kl/7UuuYCnbJO3Z9kaSMVrVxEZMSLe
YmW8Hc4ZsTnl9f05DQFy8ABpAvMLmXJQXh63BbfzjFqNbSWQfLhrubSM2Elq
xmN6EsmRyAuEeYlSnal+Di2MlViohpCbbagE2D6AZTUECIamTib6+DuLG4XO
b4GGKHR9TXu2qS1VH6hqcvdEz2MDE5OqZzAnBgcF2dvcOdTk9gAOoR1T+qKj
IJtg2X0ETbxcPqEXQoXE8VrxN0MLT5JQKTg26+csU4P2w0rEWsUsJombABEB
AAHNJU1vcmdhbiBBbGxlbiA8bW9yZ2FucmFsbGVuQGdtYWlsLmNvbT7CwFwE
EAECABAFAlG3btwJEG9pFLKaVEfeAAD7hwf+K8LN/kfgi8GTRLiTcuM+hSbm
uAeiBY+VaJIQFLzoFlt8A0hBlLNPFNNmUDxdPrMErdHgZ7HtJW/6RANuBTti
5hr3EBguH1GQyK7BbUqJGvaEX4UNRej3uyX3ufXDsIB/3NsKaTyyu+SO0+Hv
Cn2DwmlfSXcPhoarx6Turizn/WwgtTN3tqrMWxxiCKWydLH5xYuz+23BLMdc
oF/zkbF+7ddFhmyfiFh4Ej9//tsfwPj2cACU3uLTrcwCo7IxUtkrqMF/fhlm
LEqjhzDDjq9v7GNWb/5xB2xgTaucJ7/ljuS8nPlZqwCI8NlTgSqC8nyVLyjS
yVtOzkItcS0UqyW1Mg==
=V/Ia
-----END PGP PUBLIC KEY BLOCK-----

**Comment by bryan-m-hughes** [comment]
Thanks @morganrallen

**Comment by voodootikigod** [comment]
Absolutely can craft something special!

Thursday is perfect!

Cheers

*Chris Williams*

@voodootikigod <http://twitter.com/voodootikigod> | GitHub
<http://github.com/voodootikigod>

*The things I make that you should check out:*
SaferAging <http://www.saferaging.com/> | JSConf <http://jsconf.com/> |
RobotsConf <http://robotsconf.com/> | RobotsWeekly
<http://robotsweekly.com/>

Help me end the negativity on the internet, share this
<http://jsconf.eu/2011/an_end_to_negativity.html>.

**Comment by morganrallen** [comment]
So it's all good for that date (29 Thur), also Supply Frame is happy to
provide food and drink for the night.

On Sun, Jan 4, 2015 at 3:50 PM, Chris Williams <notifications@github.com>
wrote:

> Absolutely can craft something special!
>
> Thursday is perfect!
>
> Cheers
>
> *Chris Williams*
>
> @voodootikigod <http://twitter.com/voodootikigod> | GitHub
> <http://github.com/voodootikigod>
>
> *The things I make that you should check out:*
> SaferAging <http://www.saferaging.com/> | JSConf <http://jsconf.com/> |
> RobotsConf <http://robotsconf.com/> | RobotsWeekly
> <http://robotsweekly.com/>
>
> Help me end the negativity on the internet, share this
> <http://jsconf.eu/2011/an_end_to_negativity.html>.
>
> On Sun, Jan 4, 2015 at 6:41 PM, Bryan Hughes <notifications@github.com>
> wrote:
>
> > Thanks @morganrallen <https://github.com/morganrallen>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/nodebots/sf/issues/23#issuecomment-68655178>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodebots/sf/issues/23#issuecomment-68655487>.
>



-- 
http://ithoughtyouweretherobot.com
Metal and Wire

http://nolonelyguineapigs.com/
Wandering and Rambling

http://morglog.org
Old and Neglected.

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: OpenPGP.js v.1.20121007
Comment: http://openpgpjs.org

xsBNBFG3btUBB/9+/WJNOSIuc/praKPaPOweqXV5s7PGRD+HAnNWF/19YAY3
AFtfeoelhhY4sMJoobTaJzcZojznZ1kl/7UuuYCnbJO3Z9kaSMVrVxEZMSLe
YmW8Hc4ZsTnl9f05DQFy8ABpAvMLmXJQXh63BbfzjFqNbSWQfLhrubSM2Elq
xmN6EsmRyAuEeYlSnal+Di2MlViohpCbbagE2D6AZTUECIamTib6+DuLG4XO
b4GGKHR9TXu2qS1VH6hqcvdEz2MDE5OqZzAnBgcF2dvcOdTk9gAOoR1T+qKj
IJtg2X0ETbxcPqEXQoXE8VrxN0MLT5JQKTg26+csU4P2w0rEWsUsJombABEB
AAHNJU1vcmdhbiBBbGxlbiA8bW9yZ2FucmFsbGVuQGdtYWlsLmNvbT7CwFwE
EAECABAFAlG3btwJEG9pFLKaVEfeAAD7hwf+K8LN/kfgi8GTRLiTcuM+hSbm
uAeiBY+VaJIQFLzoFlt8A0hBlLNPFNNmUDxdPrMErdHgZ7HtJW/6RANuBTti
5hr3EBguH1GQyK7BbUqJGvaEX4UNRej3uyX3ufXDsIB/3NsKaTyyu+SO0+Hv
Cn2DwmlfSXcPhoarx6Turizn/WwgtTN3tqrMWxxiCKWydLH5xYuz+23BLMdc
oF/zkbF+7ddFhmyfiFh4Ej9//tsfwPj2cACU3uLTrcwCo7IxUtkrqMF/fhlm
LEqjhzDDjq9v7GNWb/5xB2xgTaucJ7/ljuS8nPlZqwCI8NlTgSqC8nyVLyjS
yVtOzkItcS0UqyW1Mg==
=V/Ia
-----END PGP PUBLIC KEY BLOCK-----

**Comment by bryan-m-hughes** [comment]
@morganrallen fantastisch! Yes, lets have them supply food and drink.

I'll try and get the meetup event up tomorrow-ish.

**Comment by voodootikigod** [comment]
quite a testament to live up to! hope to not let anyone down (and if I do,
there is the bar afterwards right?)

*Chris Williams*

@voodootikigod <http://twitter.com/voodootikigod> | GitHub
<http://github.com/voodootikigod>

*The things I make that you should check out:*
SaferAging <http://www.saferaging.com/> | JSConf <http://jsconf.com/> |
RobotsConf <http://robotsconf.com/> | RobotsWeekly
<http://robotsweekly.com/>

Help me end the negativity on the internet, share this
<http://jsconf.eu/2011/an_end_to_negativity.html>.

**Comment by dshaw** [comment]
Looks great.

**Comment by bryan-m-hughes** [comment]
San Francisco is the land of bars. I'm sure we can find something ;-)

If there are no further comments, I'll announce the meetup tomorrow morning (kinda late in the day right now IMO).

**Comment by TheAlphaNerd** [comment]
:+1:

**Comment by bryan-m-hughes** [comment]
So, the planning meeting is next week, what time would we like to meet? 6? 6:30?

Also, can you let me know if you plan to attend so I can get a head count?

**Comment by nexxy** [comment]
6:30 sounds fabulous. I will be there! :smile_cat: 

(La Trappe, right?)

**Comment by dshaw** [comment]
:beers:

**Comment by morganrallen** [comment]
Way to not be on a Thursday! I'll be there.

On Thu, Jan 8, 2015 at 11:44 PM, Dan Shaw <notifications@github.com> wrote:

> [image: :beers:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodebots/sf/issues/23#issuecomment-69303055>.
>



-- 
http://ithoughtyouweretherobot.com
Metal and Wire

http://nolonelyguineapigs.com/
Wandering and Rambling

http://morglog.org
Old and Neglected.

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: OpenPGP.js v.1.20121007
Comment: http://openpgpjs.org

xsBNBFG3btUBB/9+/WJNOSIuc/praKPaPOweqXV5s7PGRD+HAnNWF/19YAY3
AFtfeoelhhY4sMJoobTaJzcZojznZ1kl/7UuuYCnbJO3Z9kaSMVrVxEZMSLe
YmW8Hc4ZsTnl9f05DQFy8ABpAvMLmXJQXh63BbfzjFqNbSWQfLhrubSM2Elq
xmN6EsmRyAuEeYlSnal+Di2MlViohpCbbagE2D6AZTUECIamTib6+DuLG4XO
b4GGKHR9TXu2qS1VH6hqcvdEz2MDE5OqZzAnBgcF2dvcOdTk9gAOoR1T+qKj
IJtg2X0ETbxcPqEXQoXE8VrxN0MLT5JQKTg26+csU4P2w0rEWsUsJombABEB
AAHNJU1vcmdhbiBBbGxlbiA8bW9yZ2FucmFsbGVuQGdtYWlsLmNvbT7CwFwE
EAECABAFAlG3btwJEG9pFLKaVEfeAAD7hwf+K8LN/kfgi8GTRLiTcuM+hSbm
uAeiBY+VaJIQFLzoFlt8A0hBlLNPFNNmUDxdPrMErdHgZ7HtJW/6RANuBTti
5hr3EBguH1GQyK7BbUqJGvaEX4UNRej3uyX3ufXDsIB/3NsKaTyyu+SO0+Hv
Cn2DwmlfSXcPhoarx6Turizn/WwgtTN3tqrMWxxiCKWydLH5xYuz+23BLMdc
oF/zkbF+7ddFhmyfiFh4Ej9//tsfwPj2cACU3uLTrcwCo7IxUtkrqMF/fhlm
LEqjhzDDjq9v7GNWb/5xB2xgTaucJ7/ljuS8nPlZqwCI8NlTgSqC8nyVLyjS
yVtOzkItcS0UqyW1Mg==
=V/Ia
-----END PGP PUBLIC KEY BLOCK-----

**Comment by TheAlphaNerd** [comment]
See you at 6:30

**Comment by Frijol** [comment]
I'll be there! Sorry for the slow response re SupplyFrame; been out of town

**Comment by bryan-m-hughes** [comment]
6:30 at La Trappe on 1/13 (Tues) it is. See you all there! La Trappe is at 800 Greenwich St.

**Comment by nexxy** [comment]
should we try to secure reservations? is that a thing they do? has someone already done this?

**Comment by nexxy** [comment]
Nevermind! I called them and got us a table for 7 @ 6:30pm

**Comment by morganrallen** [comment]
Carp! I forgot this was tonight! Shufflin' plans, see you all at 630.

On Tue, Jan 13, 2015 at 4:38 PM, E̵̘̳̘̝ṃ̟͈͙̗̹͘i͖͇ḷ͚͔̱̰̠y͜
̩̲͕R̮̜͓̫o͉̣̦̘̖̖ͅs̫̣͜e̼͖̹̩͉͉͠ <notifications@github.com> wrote:

> Nevermind! I called them and got us a table for 7 @ 6:30pm
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodebots/sf/issues/23#issuecomment-69850033>.
>



-- 
http://ithoughtyouweretherobot.com
Metal and Wire

http://nolonelyguineapigs.com/
Wandering and Rambling

http://morglog.org
Old and Neglected.

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: OpenPGP.js v.1.20121007
Comment: http://openpgpjs.org

xsBNBFG3btUBB/9+/WJNOSIuc/praKPaPOweqXV5s7PGRD+HAnNWF/19YAY3
AFtfeoelhhY4sMJoobTaJzcZojznZ1kl/7UuuYCnbJO3Z9kaSMVrVxEZMSLe
YmW8Hc4ZsTnl9f05DQFy8ABpAvMLmXJQXh63BbfzjFqNbSWQfLhrubSM2Elq
xmN6EsmRyAuEeYlSnal+Di2MlViohpCbbagE2D6AZTUECIamTib6+DuLG4XO
b4GGKHR9TXu2qS1VH6hqcvdEz2MDE5OqZzAnBgcF2dvcOdTk9gAOoR1T+qKj
IJtg2X0ETbxcPqEXQoXE8VrxN0MLT5JQKTg26+csU4P2w0rEWsUsJombABEB
AAHNJU1vcmdhbiBBbGxlbiA8bW9yZ2FucmFsbGVuQGdtYWlsLmNvbT7CwFwE
EAECABAFAlG3btwJEG9pFLKaVEfeAAD7hwf+K8LN/kfgi8GTRLiTcuM+hSbm
uAeiBY+VaJIQFLzoFlt8A0hBlLNPFNNmUDxdPrMErdHgZ7HtJW/6RANuBTti
5hr3EBguH1GQyK7BbUqJGvaEX4UNRej3uyX3ufXDsIB/3NsKaTyyu+SO0+Hv
Cn2DwmlfSXcPhoarx6Turizn/WwgtTN3tqrMWxxiCKWydLH5xYuz+23BLMdc
oF/zkbF+7ddFhmyfiFh4Ej9//tsfwPj2cACU3uLTrcwCo7IxUtkrqMF/fhlm
LEqjhzDDjq9v7GNWb/5xB2xgTaucJ7/ljuS8nPlZqwCI8NlTgSqC8nyVLyjS
yVtOzkItcS0UqyW1Mg==
=V/Ia
-----END PGP PUBLIC KEY BLOCK-----

**Comment by bryan-m-hughes** [comment]
Thanks for taking care of that @nexxy! it was on my todo list for this afternoon, but I got busy all of a sudden and kinda forgot :(.

**Comment by Frijol** [comment]
gah, running late! See you around 6:45..

**Comment by TheAlphaNerd** [comment]
In lyft, there in 15 or so

**Comment by dshaw** [comment]
Me 3.

**Comment by dshaw** [comment]
Let's enjoy a beverage and some food and kick off planning at 7ish.

**Comment by bryan-m-hughes** [comment]
We're downstairs in the basement

**Comment by Frijol** [comment]
Recap/my notes:

Let's grow NodeBots to a global community
* Create a better central place to go for Nodebots things
 * Make it easier to find forums
 * Keep an index of groups/map them
* Make a beginner handbook/activities/links/wiki
* Get into education? Build a Nodebots-based curriculum?
* Make a projects page for Nodebots activities– maybe hackster.io tagging with nodebots would be appropriate? I'll look into it

To do:
@morganrallen follow up re space curriculum
@nexxy & @TheAlphaNerd work out plan to keep page content fresh
@nexxy & @frijol meet, talk, figure out what we're doing from our companies. Maybe each host a hack night once a month? Something we can do to explicitly make Spark + Tessel work well together? (Spark Cloud + Tessel hardware)
@dshaw * Make sure meetup page can accept donations– aiming for $10/mo to cover recurring costs
@frijol read code of conduct, get added as a contact
@bryan-m-hughes make sure code of conduct gets pushed out
@bryan-m-hughes look into making a meetup organizers meetup
@bryan-m-hughes make Twilio backend for CoC contacts
@dshaw make sure everyone has access to things they need
@dshaw create .org account
@morganrallen create robot army, lead human race to inevitable demise, die happy

My extra thoughts:
* I can envision some kind of program where we work with e.g. GEMSI to funnel makers/hackers into doing some pro bono engineering education & consulting for local underserved communities
* Would also be cool to work with openstate.cc on something
* Check out joinpolymer.com - connecting hardware people to each other
* check out alterconf
* Let's get some K'NeX

**Comment by TheAlphaNerd** [comment]
I appreciate your accurate notes regarding sky net and @morganrallen

**Comment by bryan-m-hughes** [comment]
Great writeup @Frijol, thanks!

Few more tidbits:
- @dshaw, can you add @Frijol and @nexxy as organizers on meetup.com?
- Long term goal: partner with groups such as Women Who Code, Black Girls Code, etc, and do women only, etc events. Maybe partner with other meetups and bring in a big guest
- ForwardJS is the beginning of February, and the NodeBots event is on the 6th: http://forwardjs.com/. Let me know if you want to help, and I can talk to the organizers. If demand is high, we'll need more helpers, although I'm sure I can get you in even if there isn't :)
- A thought: perhaps we could make the march meetup about k'nex.

I do have one concern though: @morganrallen is a single point of failure in the robot uprising. Perhaps we should create a contingency plan in case something untoward were to happen to him. I would hate for us to have to go without the sheer bliss of robots tearing our faces off.

**Comment by bryan-m-hughes** [comment]
Some follow up. I landed the CoC, and did some research and found these meetup groups for organizers:

http://www.meetup.com/San-Francisco-Meetup-for-Organizers/
http://www.meetup.com/sforganizer/
http://www.meetup.com/Event-Organizers-EventProfs-SF/
http://www.meetup.com/techeventorgs/
http://www.meetup.com/clswest/

Some seem to have a broad focus, some are tiny, some seem dead. None of them seem to quite fit what I had envisioned, but perhaps we should go check a few out?

**Comment by bryan-m-hughes** [comment]
Also, what does everyone think about using https://gitter.im/ (chat client that is GitHub focused)? It's free (for public repos) and has worked out really well for RobotsConf and Johnny-Five.

**Comment by voodootikigod** [comment]
Hey All,

I have a bit of concerns with some of the items in this discussion. Worse case I am there next week, so happy to discuss in person.

1. "Let's grow NodeBots to a global community" -- this has been and is still being done already, are you proposing a new, separate, sporked effort to do so or supporting the existing efforts?
2. There already is a gitter chat for the nodebots community here: https://gitter.im/nodebots
3. "Create a better central place to go for Nodebots things", might I inquire what is wrong with http://nodebots.io?
4. Keep an index of groups/map them -- we have that on nodebots.io, once again why not just support the existing effort?

Main concern is this feels like you are either frustrated or unaware of the existing efforts, I, personally, would prefer to consolidate and coordinate efforts to provide a multiple benefit effect versus fiefdoms if they could be avoided.

**Comment by bryan-m-hughes** [comment]
I didn't realize we had gitter for nodebots/, fantastic!

Regarding gitter, my thoughts was that would be very specific to NodeBots SF, e.g. used for planning by organizers, answering questions about upcoming/past events, etc. Could be useful, may be overkill :).

I'll let @Frijol and @nexxy weigh in more on the community aspect, but my understanding is that this is more of a promotion and increasing the NodeBots SF presence on nodebots.io. For example, the upcoming/past events section seems a little empty, especially for NodeBots SF :) Also, there doesn't seem to be much awareness of nodebots.io among people getting involved in NodeBots in the bay area. This is at least partly our fault for not promoting it.

**Comment by nexxy** [comment]
@voodootikigod here is my perspective:

1. This is a bit of a simplification from the context at the meeting. The idea (as I understood it) being discussed was to participate in the facilitation of a set of 'formulae' for successful learning & engagement. While I'm aware there are certainly efforts on this front, there is little information that is readily available to someone not already plugged into some kind of 'nodebots' community. _Let's fix that by creating an accessible set of resources surrounding the concept of 'nodebots'._

2. Gitter is great for developers, and (again) for people that are already 'plugged in'. I don't believe this is an accessible solution for everyone, though. I would like to see a forum that is reliable and approachable to anyone who may have even a cursory interest.

3. Nothing is wrong with nodebots.io (the domain), in fact; I think it's one of the best possible places for such a central repository! As it stands now however, it's fairly stale and in need of love. I think what came out of the meeting we had was that there are several folks interested in giving it some of that love. _Let's get it up-to-date and maybe figure out some additional features/content for the site._

4. I think 3 pretty much covers it :smile_cat:

I hope I'm not too far off the mark from what others took from the discussion, but I the feeling I got from the meeting was that the interest and commitment existed to add momentum (and maybe also focus) to existing efforts (maybe new ones too). I appreciate your concern, and I think if anything perhaps there may be some disconnects as far as existing efforts, but I didn't really pick up on any particular frustrations. 

I hope this helps!

**Comment by dshaw** [comment]
- [X] add @Frijol and @nexxy as organizers on meetup.com ( http://nodebotssf.org/ )

**Comment by nexxy** [comment]
thank you! profile updated (slightly).

**Comment by voodootikigod** [comment]
@emilyrose :+1: the simplified notes had me a concerned, your comments I agree with (as a I struggle with nodebb and the insanity it is) and glad to hear them!

Cheers

**Comment by emilyrose** [comment]
onward && upward!

**Comment by bryan-m-hughes** [comment]
Hey everyone, @voodootikigod, @TheAlphaNerd, and I were chatting in gitter earlier today. If you're not on gitter, you should join! https://gitter.im/nodebots.

So we want to do a Q&A style event, kinda like we did with Sara Chipps last October. There are two things we need to do to get ready:
1) Get a list of moderated questions together. I'm thinking we do like last time and have the first half-ish dedicated to a preselected set of questions to kinda warm up the audience. We can just put them in here.
2) Pick someone to moderate/ask questions. Any volunteers/suggestions?

**Comment by bryan-m-hughes** [comment]
Tonight's the night!

Here are a list of moderated questions for tonight I came up with. Let me know what you think @voodootikigod (and everyone else):
- What makes JSConf so unique and sought after?
- What inspired you to create JSConf?
 -If you had to pick one memory from a past JSConf that exemplified what the JSConf family is all about, what would it be?
- What inspired you to create node serialport, and were you thinking about Firmata/robotics from the outset?
- What do you think the biggest driver is for the sucess of NodeBots, as a technology and as a community?
- What are you most excited about for NodeBots right now?
- What do you think the biggest challenges are for NodeBots in the future?
- Conferences focused on hacking, not talks, are pretty unusual. Where did you get the idea for RobotsConf?
- Do you foresee RobotsConf growing into a family of conferences around the world, like JSConf?
 -What is your next big project?

Also who wants to moderate? I'm more than happy to do it, or to sit in the background and watch :)

**Comment by bryan-m-hughes** [comment]
I also got the Twilio backend implemented for the phone incident system, and open sourced the code at https://github.com/bryan-m-hughes/incident-reporter (phone numbers, etc are stored in a configuration file not checked in to the repo of course). Currently the server is running on one of my Digital Ocean droplets.

I just sent a test message, @nexxy, @Frijol, can you confirm you got the message?

**Comment by voodootikigod** [comment]
hahahah so many conference questions :)

sounds great! Anything else I can handle on the fly -- is there a safe word
I can use if I need to decline a questions.... for reasons....

*Chris Williams*

@voodootikigod <http://twitter.com/voodootikigod> | GitHub
<http://github.com/voodootikigod>

*The things I make that you should check out:*
SaferAging <http://www.saferaging.com/> | JSConf <http://jsconf.com/> |
RobotsConf <http://robotsconf.com/> | RobotsWeekly
<http://robotsweekly.com/>

Help me end the negativity on the internet, share this
<http://jsconf.eu/2011/an_end_to_negativity.html>.

**Comment by dshaw** [comment]
"Safe raging"

**Comment by voodootikigod** [comment]
@dshaw nice

**Comment by TheAlphaNerd** [comment]
My favorite safe word is 'toboggan'

**Comment by bryan-m-hughes** [comment]
"Bob Terwilliger"

Heh, I guess you're right re: conference heavy questions. I've been working on CFP's lately, so I guess I just have conferences on the brain :)

How about adding these:
- The Arduino and Raspberry Pi have been runaway successes for their ease of getting up and running with microcontrollers for the first time. Now we're seeing a number of companies, such as Spark and Electric Imp, working to make it easy to connect hardware to the cloud. If you had to guess, what would you say the next big frontier is for the hardware world?
- What is your go to hardware platform these days for your own projects, if you have one?

I'm kinda thinking about spending ~30 minutes on moderated questions before turning it over to the audience.

**Comment by bryan-m-hughes** [comment]
Last night went really well! Thanks @voodootikigod for coming out and everyone else for helping out! ❤️

**Comment by morganrallen** [comment]
Can we have a regular Story Time with @voodootikigod?

On Fri, Jan 30, 2015 at 2:45 PM, Bryan Hughes <notifications@github.com>
wrote:

> Last night went really well! Thanks @voodootikigod
> <https://github.com/voodootikigod> for coming out and everyone else for
> helping out! ❤️
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodebots/sf/issues/23#issuecomment-72283843>.
>



-- 
http://ithoughtyouweretherobot.com
Metal and Wire

http://nolonelyguineapigs.com/
Wandering and Rambling

http://morglog.org
Old and Neglected.

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: OpenPGP.js v.1.20121007
Comment: http://openpgpjs.org

xsBNBFG3btUBB/9+/WJNOSIuc/praKPaPOweqXV5s7PGRD+HAnNWF/19YAY3
AFtfeoelhhY4sMJoobTaJzcZojznZ1kl/7UuuYCnbJO3Z9kaSMVrVxEZMSLe
YmW8Hc4ZsTnl9f05DQFy8ABpAvMLmXJQXh63BbfzjFqNbSWQfLhrubSM2Elq
xmN6EsmRyAuEeYlSnal+Di2MlViohpCbbagE2D6AZTUECIamTib6+DuLG4XO
b4GGKHR9TXu2qS1VH6hqcvdEz2MDE5OqZzAnBgcF2dvcOdTk9gAOoR1T+qKj
IJtg2X0ETbxcPqEXQoXE8VrxN0MLT5JQKTg26+csU4P2w0rEWsUsJombABEB
AAHNJU1vcmdhbiBBbGxlbiA8bW9yZ2FucmFsbGVuQGdtYWlsLmNvbT7CwFwE
EAECABAFAlG3btwJEG9pFLKaVEfeAAD7hwf+K8LN/kfgi8GTRLiTcuM+hSbm
uAeiBY+VaJIQFLzoFlt8A0hBlLNPFNNmUDxdPrMErdHgZ7HtJW/6RANuBTti
5hr3EBguH1GQyK7BbUqJGvaEX4UNRej3uyX3ufXDsIB/3NsKaTyyu+SO0+Hv
Cn2DwmlfSXcPhoarx6Turizn/WwgtTN3tqrMWxxiCKWydLH5xYuz+23BLMdc
oF/zkbF+7ddFhmyfiFh4Ej9//tsfwPj2cACU3uLTrcwCo7IxUtkrqMF/fhlm
LEqjhzDDjq9v7GNWb/5xB2xgTaucJ7/ljuS8nPlZqwCI8NlTgSqC8nyVLyjS
yVtOzkItcS0UqyW1Mg==
=V/Ia
-----END PGP PUBLIC KEY BLOCK-----

**Comment by bryan-m-hughes** [comment]
Only if there's a fireplace in the background, possibly with classical music playing in the background. I was disappointed in the lack of fireplace at this space, and possible classical music playing in the background.
