### ISSUE TITLE
Workshop for kids

### ISSUE THREAD

**Issue by bryan-m-hughes** [nodebots/sf#24]
I was chatting with @melanielok the other night at the meetup, and we think that it would be really cool to host a workshop specifically for kids. What are your thoughts on what this would look like?

**Comment by melanielok** [comment]
I think it's a great idea!  I even have a bunch of kids we can experiment on.

**Comment by melanielok** [comment]
i'm not sure what all is involved in hosting a workshop but with some guidance, i'll be happy to do the logistics and organizing (find a location, organize the people and help procure materials (?) support the workshop, etc.)  if someone can help with identifying the topic and person to lead the workshop.

**Comment by dshaw** [comment]
Do we have a kids group we could collaborate with?

I've been wanting to drop in on the Creativity Museum and see what they might be interested in doing something together. Any other ideas?

http://creativity.org/

**Comment by TheAlphaNerd** [comment]
This seems like a perfect place to workshop the bots that @voodootikigod was demo’ing.=

**Comment by melanielok** [comment]
workshop around the programmable drones or the sumobots would be awesome!   i haven't been to the creativity museum but i would be happy to scope it out on Saturday when i take my son to ice skating at yerba buena gardens.  if not, we can do it at Presidio Knolls.  they would be host us if it is on a weekend.

**Comment by voodootikigod** [comment]
I am happy to help with anything I can from this distance (including but
not limited promotion)

What target of date/month are you looking at?

*Chris Williams*

@voodootikigod <http://twitter.com/voodootikigod> | GitHub
<http://github.com/voodootikigod>

*The things I make that you should check out:*
SaferAging <http://www.saferaging.com/> | JSConf <http://jsconf.com/> |
RobotsConf <http://robotsconf.com/> | RobotsWeekly
<http://robotsweekly.com/>

Help me end the negativity on the internet, share this
<http://jsconf.eu/2011/an_end_to_negativity.html>.

**Comment by melanielok** [comment]
i also have access to a huge community of parents just through my network so i can just send out a couple of emails to the the kids.  how much do workshops like this usually cost?  if we do at Presidio Knolls, i think we can just get away with just paying for their staff time which could be pretty cost-effective and we can have the kids bring their lunch and snacks (what they normally do) so this could theoretically be free.

**Comment by melanielok** [comment]
i can check out available dates for the venue but it would really need to depend on if we have someone to help teach the workshop...

**Comment by bryan-m-hughes** [comment]
I don't have any experience with kids, so I'm probably not a good choice to lead it, but I'm more than happy to lend a hand any other way I can. @dshaw, would you be willing to lead it?

As for dates, I would recommend end of February at the soonest so we have time to get our ducks in a row.  Perhaps even early-mid March?

**Comment by TheAlphaNerd** [comment]
I use to be a camp councilor, does that count?

I think giving us at least a month to flesh out details and promote would be prudent.

**Comment by melanielok** [comment]
I just spoke with Jennifer Newell, the teacher at Presidio Knolls teaching scratch in class.  She is excited to support whoever would like to lead the workshop.   Our goal is for her to teach the same drones kit curriculum at the school.

**Comment by melanielok** [comment]
Yes!  That counts!  :)

How about 15 kids?  7-9 years old sound good?

**Comment by melanielok** [comment]
I have access to a space at Presidio Knolls and an elementary school teacher (Jennifer) to lead the workshop with Myles and Bryan.  How is 3/14 as our target workshop date?  I will need about 2 weeks to recruit some (probably 15 between the ages of 7-9) students.  I am thinking 
9:30a-12:30p workshop
12:30p-1:00p lunch break
1p-4p workshop
We will test run the kit with Myles and Jennifer on 2/17 to validate the lesson plan.

**Comment by melanielok** [comment]
I got the kits yesterday!!!
![img_9367](https://cloud.githubusercontent.com/assets/10799924/6155873/8bb408a8-b1ea-11e4-8203-5caec495fcce.JPG)
![img_9368](https://cloud.githubusercontent.com/assets/10799924/6155876/8ec94238-b1ea-11e4-9996-dd9726ff5a7d.JPG)

Jennifer and I are still scheduled to meet up with Myles on 2/17 at famo.us to put them together.  Anyone else around interested in coming by are welcome.  Glynn (one of Chris' peeps) will be sending more flexbots and sumobots, but we are going to postpone the actual workshop until April.  Please let me know which Saturdays in April you all would be able to help out.

**Comment by bryan-m-hughes** [comment]
So far the weekend of the 18th is the only one I'm not free for.

What time are you meeting at famo.us?

**Comment by TheAlphaNerd** [comment]
Wahoo!!! Looks awesome.  I�m excited about the 17th.  Did you send out a calendar invite?

**Comment by melanielok** [comment]
yes.  Sorry.  Just did it today.  Added Bryan too.

**Comment by bryan-m-hughes** [comment]
Sooo...I still didn't get the calendar invite after all that :(. Can you double check my email address? bryan@theoreticalideations.com

**Comment by melanielok** [comment]
Just sent it again.  :)

**Comment by bryan-m-hughes** [comment]
thanks! worked that time :)

**Comment by bryan-m-hughes** [comment]
Ugh, so, I just realized I booked two things at the same time tonight, and I really should be at the other one, sorry about that. @TheAlphaNerd we can chat about it on Thursday at the soldering workshop.

**Comment by TheAlphaNerd** [comment]
I got it under control

**Comment by melanielok** [comment]
We are still looking for a new date for the workshop.  After talking with Linda, we are thinking we will need 2 volunteers in addition to me and Jennifer for a workshop for 10 kids to build the sumobots.  Jennifer and I are available Saturday, April 4 from 9:30am-3:30pm.  Who wants to join us for chaos and pizza with a bunch of second graders?

**Comment by bryan-m-hughes** [comment]
Are you looking for someone technical to help out if issues arise, or more for someone to help wrangle kids?

**Comment by melanielok** [comment]
Technical please.  Both Jennifer and I are good wranglers.  :D

**Comment by bryan-m-hughes** [comment]
I can help out then. Just a heads up though, I doubt I can be there earlier than 9:30 since I have to commute from Fremont, and mornings aren't exactly my forte 😉

**Comment by melanielok** [comment]
Got it.  Will have coffee ready.

**Comment by bryan-m-hughes** [comment]
Just following up with everyone, who will be there on Saturday? I'll be there, and @melanielok of course. @TheAlphaNerd, @emilyrose, @Frijol, @dshaw?

Also, I did a build of the sumobot with a Spark last night and got it working. @melanielok, I followed the wiring diagram I sent you and there were no issues.

I do have one question though: what exactly are our plans in terms of coding? Are we planning on just letting the kids build it and we flash some existing code for them to play with? Do we want them to play around with it?

If it's the former, I can write up some code real quick that will allow them to control the bot using a keyboard as if it were a game controller.

If it's the latter, do we want to program in C or JavaScript? The advantage of C is that we get to use Spark's nice web-based GUI, but have to deal with issues that crop up trying to flash the device (@emilyrose, BTW my Spark's still fail to program OTA at least half the time :-/). If we go with JavaScript, we don't have to deal with those issues, plus JavaScript/Johnny-Five is so much easier to work with compared to C, but we have to use a separate text editor, command line tools, etc.

Thoughts?

**Comment by bryan-m-hughes** [comment]
Oh also, were exactly is the event?

**Comment by melanielok** [comment]
1-Jennifer from PKS, me, Ly, you, Myles and Chris R from ETA will be there.  Max will be available by phone if we have problems.
2-Max set up the sumobot with a spark core and connected it with the school laptop.  He showed me how to do it.  Here are the instructions.  https://github.com/MaxDavila/sumobot-sparkcore/blob/master/README.md

**Comment by melanielok** [comment]
3-the plan is to have everything setup and to just have the kids calibrate the servos and use the keyboard on the computer to control the sumobots.
4-Presidio Knolls is located at 250 10th St x Folsom.

**Comment by melanielok** [comment]
Spark helped me flash all the cores so they are all connected to the school's wifi.  I've set up 5 of the laptops and will do the remaining 6 this afternoon when I am at the school.  School will be open at 8:45a Saturday morning.  Bryan/Myles--how do you take your coffee?

**Comment by emilyrose** [comment]
@bryan-m-hughes this is concerning for sure! I'm happy to try to debug this with you. 

I wonder about using voodoospark for something like this. Is that the intention here?

**Comment by bryan-m-hughes** [comment]
@emilyrose I'll DM you on twitter so we don't clutter up the convo here. Looking at the docs that @melanielok linked to, it would seem that we are using voodoospark.

@melanielok has someone written the code to get the keyboard to control the sumbot? If not, I can repurpose some code I wrote last year that does basically this: https://github.com/bryan-m-hughes/jsfest-sf-2014-nodebot

I actually don't drink coffee, but I do drink tea :)

**Comment by lynnaloo** [comment]
If you look at Max's repo here: https://github.com/MaxDavila/sumobot-sparkcore/blob/master/README.md, he's using code that's based on Rick Waldron's instructions from RobotsConf.
http://bocoup.com/weblog/assembling-preparing-robotsconf-sumobot-with-johnny-five/

**Comment by lynnaloo** [comment]
My advice (based on the Sumobots workshops we do here in Norfolk) was to have laptops pre-loaded with Node.js and the code she want the kids to use. Since they're elementary school age, they'll spend a lot of time building and decorating their bots. Then, in small groups, they can connect their bots and run the pre-loaded code to get some experience driving the bots with the keyboard. This way there are only a few Sparks on the wifi at one time and no frustrations relating to loading code. The older and more experienced kids can still play around with the code if they choose on the laptop.

**Comment by melanielok** [comment]
i had some trouble flashing the cores at school today but it was fine when I did it with Max just now.  So 1 core down, 9 more to go.  If I still have problems in the morning, I may stop by Sparkhaus on my way to school to get some help.

**Comment by chrisrhoton** [comment]
@melanielok Good meeting you today.  What's the plan for powering the Sparks.  I got the impression you were looking to go untethered on Sat.  Does that mean we'll be connecting the Sparks to the battery pack (along with the servos), or will we have some battery shields available?

**Comment by melanielok** [comment]
There is a wiring diagram at https://github.com/MaxDavila/sumobot-sparkcore/blob/master/README.md

**Comment by melanielok** [comment]
I got 1 longish USB cord from Spark in case both wifi's go down.  If anyone has another one, can you please bring it tomorrow?

**Comment by bryan-m-hughes** [comment]
:+1:

**Comment by bryan-m-hughes** [comment]
I added some documentation for getting the sumbot up and running, let me know what you think: https://github.com/bryan-m-hughes/jsfest-sf-2014-nodebot

**Comment by melanielok** [comment]
Thanks!  Lemme check it out when I get back from vacation.
