### ISSUE TITLE
ForwardJS workshop

### ISSUE THREAD

**Issue by bryan-m-hughes** [nodebots/sf#25]
Hey everyone, so @TheAlphaNerd had some stuff come up and isn't able to help out anymore tomorrow. I could really use someone else on hand to help. @dshaw, @morganrallen, @emilyrose, or @Frijol, are any of you available tomorrow from 10ish to 4ish, or know someone else who knows johnny-five/arduino enough to help?

**Comment by dshaw** [comment]
I'm locked in Node Summit prep unfortunately. Tweet out a call for contributors on the NodebotsSF account.

**Comment by bryan-m-hughes** [comment]
Good thinking! done.

**Comment by TheAlphaNerd** [comment]
It is looking like I will be able to come, but not until 2pm at the earliest.

**Comment by bryan-m-hughes** [comment]
Hardware was put back in storage, stick a fork in this one it's done :)
