### ISSUE TITLE
Future event ideas

### ISSUE THREAD

**Issue by bryan-m-hughes** [nodebots/sf#26]
So our next meetup is in a month, and we need a topic! It also might not hurt to come up with a few other ideas.

I chatted with the Airware folks at the last SFNode, and they're open to hosting at their place, and we might be able to work in a drone-themed evening too (since they're a drone company after all!)

I was also thinking that it could be fun to do some sort of hackster.io evening with @alexglow if she's interested and done touring the country in their ~~time machine~~ DeLorean.

What are some of your ideas?

**Comment by melanielok** [comment]
Drone-themed yeah!  I'd like to get one to fly.  :)

**Comment by bryan-m-hughes** [comment]
Just so we don't forget, @TheAlphaNerd suggested this: https://github.com/tableflip/lasercat-workshop/blob/master/README.md. It looks awesome.
