### ISSUE TITLE
March meetup

### ISSUE THREAD

**Issue by bryan-m-hughes** [nodebots/sf#27]
It's almost March (gah! where did the month go?), so we need to get this nailed down quickly. Since we're late getting the ball rolling on this one, I was thinking that one of us should lead it so we can get things squared away quickly.

@Frijol or @emilyrose, would one of you be willing to do a workshop on Tessel/Spark? Or, @TheAlphaNerd, would you be interested in (finally) doing the audio hacking workshop?

**Comment by emilyrose** [comment]
I'm down for a Spark workshop! We're doing the "Third Thursday" schedule, right?

**Comment by bryan-m-hughes** [comment]
Cool!

Oh right, date. Yeah, third Thursday, so 3/19.

**Comment by melanielok** [comment]
I'm up for a Spark workshop.  Lemme know if ther is something I can do to help.

**Comment by Frijol** [comment]
Always down for a workshop– would it be weird to do a combined workshop? (I want to hang out with Spark :) )

**Comment by bryan-m-hughes** [comment]
@Frijol I've been thinking about it this some, and I feel that having a combined workshop might be a bit much for one evening. I don't think it would be weird, but rather that it would make it feel more like an open hack night than a focused workshop-y thing. You can always come just to hang out :).

That said, we should definitely do a Tessel evening as well (maybe April or May?).

Also, did you and @emilyrose ever get a chance to talk about Tessel support in Spark cloud? I still think that would be amazingly awesome!

**Comment by bryan-m-hughes** [comment]
The event is scheduled: http://www.meetup.com/nodebotssf/events/220896324/

We still need a venue, and I was thinking maybe New Relic. @dshaw you have some contacts there, correct? Could you get in touch with them, or get me in touch with them?

**Comment by bryan-m-hughes** [comment]
So I may have a lead on a venue at Zoosk.

**Comment by melanielok** [comment]
If you absolutely can't find a place, I can host at my house.  I can seat 12 comfortably around my dining room table.  :D

**Comment by bryan-m-hughes** [comment]
Zoosk is in, we have our venue! I'll update the meetup.com page and announce the event tomorrow morning

**Comment by MaxZoosk** [comment]
Hi, I was actually folllowing the conversation here and thats when I noticed you were looking for a place

**Comment by bryan-m-hughes** [comment]
Hey everyone, tomorrow night is the night! I just wanted to follow up with everyone, especially @MaxZoosk and @emilyrose to see how things are coming along. Do you need anything from me?

I've got a meeting that ends at 5 tomorrow, and I'm planning on heading over as soon as that's done, so I'm guessing I'll be there around 5:20-5:30

**Comment by MaxZoosk** [comment]
Hello!

Everything looks set on my end. Zoosk is at 989 Market st. Its the Blick Art supply building, btw. We are going to be on the 6th floor. There will be someone in the lobby escorting people up or if they happen to know to tell the security guard they are looking for Max, they can go up that way as well. I will be up on 6 where we have a large meeting room.

If you want to email me at maxb at zoosk com and I will send you my phone number so we can have more speedy communication for tomorrow.

-Max

**Comment by TheAlphaNerd** [comment]
What is the deal for bikes?

**Comment by MaxZoosk** [comment]
I just told the guy who will be downstairs to be prepared to deal with people with bicycles. He will take you to the 4th floor where you can stash your bike in a room thats behind a key card lock. Then you will need him or me to help you get your bike out when you are ready to leave. Alternatively there are some bike posts you can lock your bike too just outside the building: https://www.evernote.com/shard/s212/sh/d2d30322-b6bd-431c-8d6b-6ece6c5638fd/e9c76ca7f60543a87bb45cf329854654/deep/0/Hallidie-Plaza---Google-Maps.png
