### ISSUE TITLE
Planning Meeting, May 2015 edition

### ISSUE THREAD

**Issue by bryan-m-hughes** [nodebots/sf#30]
Hey everyone, so we've been planning things kinda month to month lately, and it kinda sucks. I propose we get together over dinner and plan out future events like we did last fall. I'm hoping to make planning less chaotic so we don't end up in a bind having to skip a month like we did for April.

Anyone else in? I'm free this Friday, next Monday, and next Tuesday.

cc @dshaw @TheAlphaNerd @emilyrose @Frijol

**Comment by TheAlphaNerd** [comment]
Next Monday and tuesday are wide open for me :D

**Comment by melanielok** [comment]
Monday and Tuesday work for me too.

**Comment by Frijol** [comment]
Monday/Tuesday (the 4th & 5th, right?) are good for me too.

**Comment by TheAlphaNerd** [comment]
Monday the 4th works better for me!

**Comment by bryan-m-hughes** [comment]
I'm going to see Welcome to Me on the 4th as part of the SFIFFS (http://www.sffs.org/sfiff58/program/welcome-to-me), but it should be done at 7:30. I have nothing scheduled on Tuesday.

Also, where do we want to go?

**Comment by dshaw** [comment]
Monday or Tuesday both work good for me.

**Comment by TheAlphaNerd** [comment]
I'm a liar... Tuesday works for me too.

Maybe we could go to --> http://somastreatfoodpark.com/

Lots of food trucks means lots of options!

**Comment by bryan-m-hughes** [comment]
Hmm...I'm torn on Streat Food. It's super close to the Rdio office and I go there every week. It's awesome! But I go there every week. Hmm... :)

**Comment by melanielok** [comment]
Basil Canteen is good too.  http://www.yelp.com/biz/basil-canteen-san-francisco

**Comment by bryan-m-hughes** [comment]
I like Thai!

**Comment by TheAlphaNerd** [comment]
+! for thai

**Comment by bryan-m-hughes** [comment]
@alexglow, interested/available in joining us? We can talk as a group about your bike hack and possibly come up with something a little more off the wall for it :)

**Comment by bryan-m-hughes** [comment]
So let's set some specifics: How does Basil Canteen at 7 on Tuesday May 5th sound?

**Comment by melanielok** [comment]
Works for me

**Comment by dshaw** [comment]
Basil Canteen 7pm tomorrow? It's on the calendar, so it's real!

**Comment by bryan-m-hughes** [comment]
woo! Should we make a res? I think there will be 7-8

**Comment by TheAlphaNerd** [comment]
I got the cal invite� looking forward to it!

Tomorrow is also beerjs if people want to swing by after dinner.

**Comment by bryan-m-hughes** [comment]
I went ahead and made a reservation for 8. See you then!

**Comment by melanielok** [comment]
Excellent!  See you all tonight.

**Comment by alexglow** [comment]
w00t! See you all at 7 :)

**Comment by melanielok** [comment]
On my way!

**Comment by bryan-m-hughes** [comment]
My notes from last night:

May: @ykro
June: Bike hacking with @alexglow coinciding with NodeConf, possibly at Pier 9 after @melanielok's tour w/ the Norfolk crew
July: NodeBots Day
August: Audio hacking with @TheAlphaNerd 
September: Tessel2 with @Frijol and crew
October: Halloween hacks - shoes, costumes, pumpkins, etc

**Comment by Frijol** [comment]
Should we make issues for each of these?

**Comment by bryan-m-hughes** [comment]
@Frijol good thinking

**Comment by bryan-m-hughes** [comment]
I filed #32, #33, #34, and #35. NodeBots Day already has a slack channel for planning that event, so I didn't create a separate issue here.

Ping @dshaw for access
